<a href="https://colab.research.google.com/github/Sneha8126/Python-Assignment/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr=np.array([4,5,6])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10,3)

array([1, 4, 7])

In [ ]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [ ]:
myarr=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [ ]:
print("Shape: ",myarr.shape)
print("Size: ",myarr.size)
print("Dimension: ",myarr.ndim)
print("Data Type: ",myarr.dtype)

Shape:  (3, 3)
Size:  9
Dimension:  2
Data Type:  int64


In [ ]:
myarr=np.array([[[10,20,30],[40,50,60],[70,80,90]],[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
print("Shape: ",myarr.shape)
print("Size: ",myarr.size)
print("Dimension: ",myarr.ndim)
print("Data Type: ",myarr.dtype)

Shape:  (2, 3, 3)
Size:  18
Dimension:  3
Data Type:  int64


In [ ]:
myarr=np.array([[10,20,30],[40,50,60],[70,80,90]] ,dtype='float32')

In [ ]:
myarr

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]], dtype=float32)

In [ ]:
myarr=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [ ]:
myarr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arr_int=myarr.astype(np.float32)

In [ ]:
print(arr_int)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
reshaped=arr.reshape((3,2))
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(reshaped.shape)

(3, 2)


In [ ]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

# Indexing and Slicing

In [ ]:
arr[0]

array([1, 2, 3])

In [ ]:
arr[1]

array([4, 5, 6])

In [ ]:
flat=arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [ ]:
print(flat[0])

1


In [ ]:
print(flat[1])
print(flat[2])
print(flat[3])
print(flat[4])

2
3
4
5


In [ ]:
print(flat[1:3])

[2 3]


In [ ]:
print(flat[:3])
print(flat[3:])

[1 2 3]
[4 5 6]


In [ ]:
print(flat[::-1])

[6 5 4 3 2 1]


In [ ]:
print(flat[::2])

[1 3 5]


In [ ]:
arr = np.array([10,20,30,40,50])
idx = [0,2,4]
print(arr[idx])

[10 30 50]


In [ ]:
mask = arr>25
print(arr[mask])

[30 40 50]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr[0][1])

2


In [ ]:
print(arr[0,1])

2


In [ ]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = []

# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)

print(result)  # Output: [1, 4, 9, 16, 25]

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [1 4 9 16 25]

[ 1  4  9 16 25]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2  # Element-wise addition
print(result)  # Output: [11 22 33]

[11 22 33]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]

[[2 4 6]
 [5 7 9]]


In [ ]:
# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
